### ISSUE TITLE
 Mongoid::Errors::StaleDocument: Attempted to update a stale document: raised on fresh object..actually it should not

### ISSUE THREAD

**Issue by sandipransing** [burgalon/mongoid_optimistic_locking#12] opened 2013-03-06 07:58 UTC
`s = Sequence.last
 => #<Sequence _id: 5135d9d82cb6f35e2d000001, _type: nil, _lock_version: 0, project_id: "5110f3462cb6f313a5000003", payment: 0, receipt: 0, transfer: 0> 
1.9.3p194 :033 > s.transfer +=1
 => 1 
1.9.3p194 :034 > s.changes
 => {"_lock_version"=>[1, 0], "transfer"=>[0, 1]} 
1.9.3p194 :035 > s.save

Mongoid::Errors::StaleDocument: Attempted to update a stale document: Sequence

I am not understanding why above code is raising Mongoid::Errors::StaleDocument: exception..?

**Comment by burgalon** [comment] 2013-03-06 15:43
I tested a similar case in console and could not reproduce this.
You might have had something happening in the database while you were doing this?
Please write a spec that fails and submit a pull request and I'll try to fix it.
Until then, I'm closing the bug

**Closed as completed by burgalon** 2013-03-06 15:43 UTC

**Comment by proton** [comment] 2014-07-17 12:45
I reproduced this:
When I include Mongoid::OptimisticLocking to already existing model, I should execute Model.update_all(:_lock_version => 0).

**Comment by proton** [comment] 2014-07-17 14:36
Another way to reproduce this: use consistency: :eventual in replica set.
Fixed in this branch: https://github.com/Natural-Intelligence/mongoid_optimistic_locking/tree/replica_set_support
